### PR TITLE
Add tls example

### PR DESCRIPTION
**Pull request by devashishdxt**

### CODE REVIEW

**Comment by seanwatters** [comment]
I see that this isn't currently building but would love to know if there are any already known blockers to using TLS with `tonic-web-wasm-client`. 

Awesome crate btw 👍🏻

**Comment by devashishdxt** [comment]
> I see that this isn't currently building but would love to know if there are any already known blockers to using TLS with `tonic-web-wasm-client`. 
> 
> 
> 
> Awesome crate btw 👍🏻 

This example doesn't build because it uses self signed TLS certificate and I don't know how to configure browser on GitHub actions to accept that certificate.

I'm not aware of any blockers for using TLS with this crate but feel free to open an issue if you encounter one.

**Comment by seanwatters** [comment]
> > I see that this isn't currently building but would love to know if there are any already known blockers to using TLS with `tonic-web-wasm-client`.
> > Awesome crate btw 👍🏻
> 
> This example doesn't build because it uses self signed TLS certificate and I don't know how to configure browser on GitHub actions to accept that certificate.
> 
> I'm not aware of any blockers for using TLS with this crate but feel free to open an issue if you encounter one.

Interesting. I keep getting a Sock2 related error any time I try to use the TLS feature within my WASM module. I need to build with the TLS feature enabled again to grab the error message, but if that sounds familiar to you at all or you have a fix off the top of your head lmk!

**Comment by seanwatters** [comment]
@devashishdxt, so this is my client code, and my server code. I'm currently getting CORS errors (which I know sometimes means that there's actually some other underlying error) can you maybe help me see what i'm missing?

I'm worried that maybe my keys were generated incorrectly? 

```bash
openssl req -x509 -newkey rsa:2048 -nodes -keyout server.key -out server.crt -subj "/CN=localhost"
```

```rust
// client
use once_cell::sync::OnceCell;
use parking_lot::Mutex;
use std::sync::Arc;

use tonic_web_wasm_client::Client;

static APP_CLIENT: OnceCell<Arc<Mutex<ApplicationClient<Client>>>> = OnceCell::new();

pub(crate) fn get_app_client() -> ApplicationClient<Client> {
    let client = APP_CLIENT.get_or_init(|| {
        let base_url = "https://localhost:50052".to_string();

        let client = ApplicationClient::new(Client::new(base_url));

        Arc::new(Mutex::new(client))
    });

    let lock = client.lock();
    let client = lock.clone();

    drop(lock);

    client
}
```

```rust
// server

use std::sync::Arc;
use tokio::sync::Mutex;

use tonic::transport::{Identity, ServerTlsConfig};
use tonic::{transport::Server, Request, Response, Status};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cert = tokio::fs::read("server.crt").await?;
    let key = tokio::fs::read("server.key").await?;
    let identity = Identity::from_pem(cert, key);

    let application_service = ApplicationService {
        db_client: Arc::new(Mutex::new(get_db_client().await)),
    };

    let addr = "[::1]:50052".parse().unwrap();
    println!("Server running at: {}", addr);

    Server::builder()
        .tls_config(ServerTlsConfig::new().identity(identity))?
        .accept_http1(true)
        .add_service(tonic_web::enable(ApplicationServer::new(
            application_service,
        )))
        .serve(addr)
        .await?;

    Ok(())
}
```

```toml
## Cargo.toml

[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
ordinal_crypto = { workspace = true }
tokio = { version = "1.29.1", features = ["full"] }
tokio-stream = "0.1.14"

tonic = { version = "0.9.2", features = ["tls", "transport", "codegen"] }
tonic-web = "0.9.2"
tower-http = { version = "0.4.3", features = ["cors"] }

prost = "0.11.9"
prost-types = "0.11.9"

parking_lot = "0.12.1"
jemallocator = "0.5.0"
base64 = "0.21.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.26"
bcrypt = "0.15.0"
jsonwebtoken = "8.3.0"
http = "0.2.9"

[dependencies.uuid]
version = "1.4.1"
features = ["v4", "fast-rng", "macro-diagnostics"]

[build-dependencies]
tonic-build = "0.9.2"
```

**Comment by seanwatters** [comment]
here's a quick PR to address the hard-coded `SameOrigin` issue: https://github.com/devashishdxt/tonic-web-wasm-client/pull/43

**Comment by seanwatters** [comment]
okay, sorry for blowing this PR up so much with comments. I figured out that my issue was just that I had never configured TLS certs before for localhost and just needed to add all the stuff to keychains on MacOS so that the browser didn't get sad.

**Pull request closed without merging**
